// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Permission struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Code        string         `json:"code"`
	Description sql.NullString `json:"description"`
	ParentID    sql.NullInt32  `json:"parent_id"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserPermission struct {
	UserID       int32 `json:"user_id"`
	PermissionID int32 `json:"permission_id"`
}
