// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_permissions.sql

package db

import (
	"context"

	"github.com/lib/pq"
)

const assignUserPermissions = `-- name: AssignUserPermissions :exec
INSERT INTO user_permissions (user_id, permission_id)
SELECT $1, unnest($2::int[])
ON CONFLICT DO NOTHING
`

type AssignUserPermissionsParams struct {
	UserID  int32   `json:"user_id"`
	Column2 []int32 `json:"column_2"`
}

func (q *Queries) AssignUserPermissions(ctx context.Context, arg AssignUserPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, assignUserPermissions, arg.UserID, pq.Array(arg.Column2))
	return err
}

const detachUserPermissions = `-- name: DetachUserPermissions :exec
DELETE FROM user_permissions
WHERE user_id = $1
  AND permission_id = ANY($2::int[])
`

type DetachUserPermissionsParams struct {
	UserID  int32   `json:"user_id"`
	Column2 []int32 `json:"column_2"`
}

func (q *Queries) DetachUserPermissions(ctx context.Context, arg DetachUserPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, detachUserPermissions, arg.UserID, pq.Array(arg.Column2))
	return err
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT p.id, p.name, p.code, p.description, p.parent_id, p.created_at, p.updated_at
FROM permissions p
JOIN user_permissions up ON p.id = up.permission_id
WHERE up.user_id = $1
ORDER BY p.id
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID int32) ([]Permission, error) {
	rows, err := q.db.QueryContext(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.ParentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncUserPermissions = `-- name: SyncUserPermissions :exec
WITH desired AS (
  SELECT unnest($2::int[]) AS permission_id
)
DELETE FROM user_permissions
WHERE user_id = $1
  AND permission_id NOT IN (SELECT permission_id FROM desired)
`

type SyncUserPermissionsParams struct {
	UserID  int32   `json:"user_id"`
	Column2 []int32 `json:"column_2"`
}

func (q *Queries) SyncUserPermissions(ctx context.Context, arg SyncUserPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, syncUserPermissions, arg.UserID, pq.Array(arg.Column2))
	return err
}
